name: Continuous Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant Permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew clean build
      - name: Create or Update GitHub Release (Continuous)
        uses: softprops/action-gh-release@v1
        with:
          name: Continuous Build
          tag_name: continuous
          files: plotsquared-bukkit/build/libs/*.jar
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
